name: flutter_weather_bg
description: Provide a variety of weather background animation effects, covering 15 weather types, including sunny,rain,snow...
version: 2.8.3
homepage: https://github.com/xiaweizi/flutter_weather_bg

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  

flutter:
  assets:
    - images/
